version: "3.9"

services:
  banana-cpu:
    image: banana-leaf:cpu
    build:
      context: .
      args:
        BASE_IMAGE: pytorch/pytorch:2.3.1-cpu
    working_dir: /app
    volumes:
      - ./:/app
      - ./data:/data          # ใส่ dataset ไว้ที่ ./data บนเครื่องเรา
      - ./runs:/app/runs      # เก็บผลลัพธ์/โมเดล
    environment:
      - DATA_DIR=/data        # ให้สคริปต์อ้างอิง path นี้
      - OUTPUT_DIR=/app/runs
    tty: true

  banana-gpu:
    image: banana-leaf:gpu
    build:
      context: .
      args:
        BASE_IMAGE: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime
    working_dir: /app
    volumes:
      - ./:/app
      - ./data:/data
      - ./runs:/app/runs
    environment:
      - DATA_DIR=/data
      - OUTPUT_DIR=/app/runs
    tty: true
    # ต้องมี NVIDIA Container Toolkit ติดตั้งในโฮสต์
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
