services:
  banana-cpu:
    build:
      context: .
      args:
        TORCH_CHANNEL: "cu121"
    image: banana-leaf:cpu
    working_dir: /app
    volumes:
      - ./:/app
      - ./dataset:/app/dataset
      - ./output:/app/output  
    tty: true

  banana-gpu:
    build:
      context: .
      args:
        TORCH_CHANNEL: "cu121"
    image: banana-leaf:gpu
    working_dir: /app
    volumes:
      - ./:/app
      - ./dataset:/app/dataset
      - ./output:/app/output  

    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
